#!/usr/bin/env bash
# running Best School for  with while else if and elif
myvar=1
while [ $myvar -le 10 ]
do
if [ $myvar -eq 4 ] 
then echo bad luck
elif [ $myvar -eq 8 ]
then echo good luck
else 
 echo Best School
fi        
((myvar++))        
done
