#!/usr/bin/env bash
# running Best School for  with while else if and elif
myvar=1
while [ $myvar -le 10 ]
do
if [ $myvar -eq 4 ] 
then echo Bad Luck
elif [ $myvar -eq 8 ]
then echo Good Luck
else 
 echo Best School
fi        
((myvar++))        
done
