#!/usr/bin/env bash
# make numbers and case and while or something
myvar=1
while [ $myvar -le 20 ]
do
case $myvar in
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
*) echo $myvar
esac
(($myvar++))
        
done
